// SPDX-License-Identifier: MIT OR Unlicense
// Autogenerated using the Scaffold feature in wawa.Editors.
// Code generated by wawa.Editors is in public domain.
// Source: https://github.com/Emik03/wawa

using System;
using UnityEngine;
using Wawa.Modules;
using Random = UnityEngine.Random;

/// <summary>On the Subject of <see cref="Solvable"/>.</summary>
public sealed class Solvable : ModdedModule
{
    protected override void OnActivate()
    {
        Log("Hello, World! ma o, toki!");
    }
}
